export class Technique
{
    id:string;
    name:string;
    genre:string;
    instrument:string;
    description:string;
    allyEffect:string|null;
    allyEffectIntesity:number|null;
    isAllySingleTarget:boolean|null;
    damage:number|null;
    opponentEffect:string|null;
    opponentEffectIntensity:number|null;
    opponentEffectProbability:number|null;
    isOpponentSingleTarget:boolean|null;
    evolutionOf:string|null;
    constructor(
        id:string,
        name:string,
        genre:string,
        instrument:string,
        description:string,
        allyEffect:string|null,
        allyEffectIntesity:number|null,
        isAllySingleTarget:boolean|null,
        damage:number|null,
        opponentEffect:string|null,
        opponentEffectIntensity:number|null,
        opponentEffectProbability:number|null,
        isOpponentSingleTarget:boolean|null,
        evolutionOf:string|null)
    {
        this.id=id;
        this.name=name;
        this.genre=genre;
        this.instrument=instrument;
        this.description=description;
        this.allyEffect=allyEffect;
        this.allyEffectIntesity=allyEffectIntesity;
        this.isAllySingleTarget=isAllySingleTarget;
        this.damage=damage;
        this.opponentEffect=opponentEffect;
        this.opponentEffectIntensity=opponentEffectIntensity;
        this.opponentEffectProbability=opponentEffectProbability;
        this.isOpponentSingleTarget=isOpponentSingleTarget;
        this.evolutionOf=evolutionOf;
    }
}